services:
  db:
    platform: linux/arm64
    image: mariadb:latest
    hostname: db-metalake
    container_name: db-metalake
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3303:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 5s
      timeout: 3s
      retries: 3

  storage:
    platform: linux/arm64
    image: minio/minio:latest
    hostname: storage-metalake
    container_name: storage-metalake
    restart: on-failure
    environment:
      MINIO_ROOT_USER: ${STORAGE_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${STORAGE_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage:/storage
    networks:
      - storage
    command: server --console-address ":9001" /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s

  server:
    platform: linux/arm64
    hostname: server-metalake
    container_name: server-metalake
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
      target: local
      args:
        ENV: local
        WORK_DIR: /workdir
        INSTALL_DIR: /opt/install
    ports:
      - "8003:8000"
    volumes:
      - .:/workdir
    networks:
      - db
      - storage
      - server
    depends_on:
      db:
        condition: service_healthy
      storage:
        condition: service_healthy
    command: >
      bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

#  prometheus:
#    platform: linux/arm64
#    image: prom/prometheus:latest
#    hostname: prometheus
#    container_name: prometheus
#    restart: unless-stopped
#    ports:
#      - 9090:9090
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
#      - prometheus:/prometheus
#    networks:
#      - server
#    depends_on:
#      - server

networks:
  db:
    name: db-metalake
    driver: bridge
  storage:
    name: storage-metalake
    driver: bridge
  server:
    name: server-metalake
    driver: bridge

volumes:
  db:
    name: db-metalake
  storage:
    name: storage-metalake
#  prometheus:
#    name: prometheus-summary
