services:
  db:
    platform: linux/arm64
    image: mariadb:11.4.8
    hostname: db-metalake
    container_name: db-metalake
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3303:3306"
    volumes:
      - db:/var/lib/mysql/data
    networks:
      - db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 3s
      interval: 5s
      timeout: 3s
      retries: 3

  server:
    platform: linux/arm64
    hostname: server-metalake
    container_name: server-metalake
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
      target: local
      args:
        ENV: local
        WORK_DIR: /workdir
        INSTALL_DIR: /opt/install
    ports:
      - "8003:8000"
    volumes:
      - .:/workdir
    networks:
      - db
      - server
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

#  prometheus:
#    platform: linux/arm64
#    image: prom/prometheus:latest
#    hostname: prometheus
#    container_name: prometheus
#    restart: unless-stopped
#    ports:
#      - 9090:9090
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
#      - prometheus:/prometheus
#    networks:
#      - server
#    depends_on:
#      - server

networks:
  db:
    name: db-metalake
    driver: bridge
  server:
    name: server-metalake
    driver: bridge

volumes:
  db:
    name: db-metalake
#  prometheus:
#    name: prometheus-summary
